# Generated by Django 3.1.7 on 2021-05-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='collection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
    ]
